using UnityEngine;
using UnityEditor;
using UnityEditor.Animations;
using UnityEditor.SceneManagement;
using UnityEngine.SceneManagement;
using TMPro;
using System.Linq;
namespace WoollyArena.Editor {
public static class ArenaBuilder {
 const string Root="Assets/Woolly/";
 static Material Mat(string name,Color c,float smooth=.1f){string p=Root+"Materials/"+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(p);if(!m){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(m,p);}m.SetColor("_BaseColor",c);m.SetFloat("_Smoothness",smooth);return m;}
 static GameObject Shape(string name,PrimitiveType type,Vector3 pos,Vector3 scale,Material mat,Transform parent=null,bool collision=true){var g=GameObject.CreatePrimitive(type);g.name=name;g.transform.SetParent(parent,false);g.transform.localPosition=pos;g.transform.localScale=scale;g.GetComponent<Renderer>().sharedMaterial=mat;if(!collision)Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 [MenuItem("Woolly/Build Test Arena")]
 public static string Build(){
  if(EditorApplication.isPlaying)throw new System.Exception("Stop play first");
  var importer=(ModelImporter)AssetImporter.GetAtPath(Root+"Art/Woolly.fbx");importer.animationType=ModelImporterAnimationType.Generic;importer.importAnimation=true;importer.animationCompression=ModelImporterAnimationCompression.Off;importer.optimizeGameObjects=false;
  var clips=importer.defaultClipAnimations;foreach(var c in clips){c.name=c.name.Split('|').Last();c.loopTime=c.name!="Shoot";c.loopPose=c.loopTime;c.lockRootRotation=true;c.lockRootHeightY=true;c.lockRootPositionXZ=true;}importer.clipAnimations=clips;importer.SaveAndReimport();
  var ti=(TextureImporter)AssetImporter.GetAtPath(Root+"Art/Woolly_Normal.png");ti.textureType=TextureImporterType.NormalMap;ti.SaveAndReimport();
  var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);
  RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.ambientLight=new Color(.64f,.7f,.8f);RenderSettings.fog=false;
  var grass=Mat("Arena Teal",new Color(.105f,.39f,.34f));var grass2=Mat("Tile Teal",new Color(.12f,.43f,.365f));var sand=Mat("Path Sand",new Color(.64f,.55f,.36f));var wall=Mat("Cover Navy",new Color(.16f,.24f,.32f));var trim=Mat("Cover Top",new Color(.32f,.46f,.49f));var gold=Mat("Signal Gold",new Color(1,.69f,.17f));var dark=Mat("Charcoal",new Color(.075f,.10f,.16f));var red=Mat("Target Coral",new Color(.95f,.28f,.22f));var white=Mat("Target Cream",new Color(.95f,.87f,.66f));
  var environment=new GameObject("Arena_Geometry");Shape("Ground",PrimitiveType.Cube,new Vector3(0,-.2f,0),new Vector3(24,.4f,22),grass,environment.transform);
  for(int x=-5;x<=5;x++)for(int z=-5;z<=5;z++)if((x+z)%2==0)Shape("FloorTile",PrimitiveType.Cube,new Vector3(x*2,.002f,z*2),new Vector3(1.98f,.012f,1.98f),grass2,environment.transform,false);
  Shape("CentralLane",PrimitiveType.Cube,new Vector3(0,.015f,1),new Vector3(3.8f,.02f,19),sand,environment.transform,false);
  Vector3[] covers={new Vector3(-5,.6f,0),new Vector3(5,.6f,0),new Vector3(-3,.6f,4),new Vector3(3,.6f,4),new Vector3(-6,.6f,-5),new Vector3(6,.6f,-5)};
  foreach(var p in covers){Shape("Cover",PrimitiveType.Cube,p,new Vector3(2.4f,1.2f,1.5f),wall,environment.transform);Shape("CoverCap",PrimitiveType.Cube,p+Vector3.up*.65f,new Vector3(2.5f,.15f,1.6f),trim,environment.transform);}
  foreach(float x in new[]{-12f,12f})Shape("Boundary",PrimitiveType.Cube,new Vector3(x,.75f,0),new Vector3(.5f,1.5f,22),wall,environment.transform);
  foreach(float z in new[]{-11f,11f})Shape("Boundary",PrimitiveType.Cube,new Vector3(0,.75f,z),new Vector3(24,1.5f,.5f),wall,environment.transform);
  for(int i=0;i<5;i++){var p=new Vector3((i-2)*3.3f,0,7+(i%2)*1.3f);var g=new GameObject("Target_"+(i+1));g.transform.position=p;var col=g.AddComponent<CapsuleCollider>();col.center=Vector3.up*.9f;col.height=1.8f;col.radius=.48f;var d=g.AddComponent<TargetDummy>();Shape("Body",PrimitiveType.Capsule,new Vector3(0,.9f,0),new Vector3(.85f,.6f,.65f),red,g.transform,false);Shape("Face",PrimitiveType.Cylinder,new Vector3(0,1.12f,-.34f),new Vector3(.58f,.035f,.58f),white,g.transform,false).transform.localRotation=Quaternion.Euler(90,0,0);Shape("Bullseye",PrimitiveType.Cylinder,new Vector3(0,1.12f,-.39f),new Vector3(.25f,.02f,.25f),red,g.transform,false).transform.localRotation=Quaternion.Euler(90,0,0);Shape("Base",PrimitiveType.Cylinder,new Vector3(0,.06f,0),new Vector3(1.2f,.06f,1.2f),dark,g.transform,false);Shape("HealthBack",PrimitiveType.Cube,new Vector3(0,1.85f,0),new Vector3(.9f,.11f,.1f),dark,g.transform,false);d.healthFill=Shape("Health",PrimitiveType.Cube,new Vector3(0,1.87f,-.06f),new Vector3(.8f,.07f,.08f),gold,g.transform,false).transform;}
  var light=new GameObject("Sun").AddComponent<Light>();light.type=LightType.Directional;light.intensity=1.15f;light.shadows=LightShadows.Soft;light.transform.rotation=Quaternion.Euler(48,-35,0);
  var player=new GameObject("Woolly_Player");player.layer=2;player.transform.position=new Vector3(0,.05f,0);var cc=player.AddComponent<CharacterController>();cc.height=1.65f;cc.center=new Vector3(0,.86f,0);cc.radius=.4f;cc.stepOffset=.25f;cc.skinWidth=.04f;
  var model=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(Root+"Art/Woolly.fbx"));model.name="Visual";model.transform.SetParent(player.transform,false);
  var bodyMat=Mat("Woolly Body",Color.white,.22f);bodyMat.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"Art/Woolly_BaseColor.png"));bodyMat.SetTexture("_BumpMap",AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"Art/Woolly_Normal.png"));bodyMat.EnableKeyword("_NORMALMAP");bodyMat.SetFloat("_BumpScale",.45f);
  foreach(var r in model.GetComponentsInChildren<Renderer>()){r.gameObject.layer=2;var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++){var n=ms[i].name;if(n.Contains("Woolly"))ms[i]=bodyMat;else ms[i]=Mat(n,n.Contains("Amber")?new Color(.46f,.20f,.07f):n.Contains("Brass")?new Color(.9f,.64f,.18f):n.Contains("edges")?new Color(.3f,.47f,.63f):n.Contains("Recesses")?new Color(.04f,.07f,.1f):new Color(.10f,.22f,.34f),.28f);}r.sharedMaterials=ms;}
  var anim=model.GetComponent<Animator>();if(!anim)anim=model.AddComponent<Animator>();anim.applyRootMotion=false;anim.cullingMode=AnimatorCullingMode.AlwaysAnimate;
  var imported=AssetDatabase.LoadAllAssetsAtPath(Root+"Art/Woolly.fbx").OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__")).ToDictionary(c=>c.name);
  string acPath=Root+"Animations/Woolly.controller";AssetDatabase.DeleteAsset(acPath);var controller=AnimatorController.CreateAnimatorControllerAtPath(acPath);controller.AddParameter("Speed",AnimatorControllerParameterType.Float);controller.AddParameter(new AnimatorControllerParameter{name="Playback",type=AnimatorControllerParameterType.Float,defaultFloat=1});controller.AddParameter("Fire",AnimatorControllerParameterType.Trigger);
  var sm=controller.layers[0].stateMachine;var state=sm.AddState("Locomotion");var tree=new BlendTree{name="Idle Walk Run",blendType=BlendTreeType.Simple1D,blendParameter="Speed",useAutomaticThresholds=false};AssetDatabase.AddObjectToAsset(tree,controller);tree.AddChild(imported["Idle"],0);tree.AddChild(imported["Walk"],.9f);tree.AddChild(imported["Run"],2.8f);var children=tree.children;children[1].timeScale=1.5f;tree.children=children;state.motion=tree;state.speedParameter="Playback";state.speedParameterActive=true;sm.defaultState=state;
  var mask=new AvatarMask();mask.name="Upper Body";mask.AddTransformPath(model.transform,true);for(int i=0;i<mask.transformCount;i++){string p=mask.GetTransformPath(i);p=p=="Visual"?"":p.Substring("Visual/".Length);mask.SetTransformPath(i,p);mask.SetTransformActive(i,p.Contains("Spine")||p.Contains("Shoulder")||p.Contains("Arm")||p.Contains("Hand")||p.Contains("Grip_")||p.Contains("Revolver")||p.Contains("Muzzle")||p.Contains("Head")||p.Contains("Neck"));}string maskPath=Root+"Animations/UpperBody.mask";AssetDatabase.DeleteAsset(maskPath);AssetDatabase.CreateAsset(mask,maskPath);
  controller.AddLayer("Upper Body Fire");var layers=controller.layers;layers[1].defaultWeight=1;layers[1].avatarMask=mask;controller.layers=layers;var fireSM=controller.layers[1].stateMachine;var ready=fireSM.AddState("Ready");fireSM.defaultState=ready;var fire=fireSM.AddState("Shoot");fire.motion=imported["Shoot"];var enter=fireSM.AddAnyStateTransition(fire);enter.hasExitTime=false;enter.duration=.035f;enter.canTransitionToSelf=true;enter.AddCondition(AnimatorConditionMode.If,0,"Fire");var leave=fire.AddTransition(ready);leave.hasExitTime=true;leave.exitTime=.94f;leave.duration=.08f;anim.runtimeAnimatorController=controller;
  var runtime=player.AddComponent<ArenaPlayer>();runtime.visual=model.transform;runtime.animator=anim;runtime.muzzle=model.GetComponentsInChildren<Transform>().First(t=>t.name=="Muzzle");var fx=new GameObject("ShotPool").AddComponent<ShotEffects>();fx.tracerMaterial=Mat("Tracer",new Color(1,.82f,.26f));runtime.effects=fx;
  var camera=new GameObject("Main Camera").AddComponent<Camera>();camera.tag="MainCamera";camera.orthographic=true;camera.orthographicSize=5.8f;camera.nearClipPlane=.1f;camera.farClipPlane=80;camera.backgroundColor=new Color(.045f,.075f,.11f);camera.clearFlags=CameraClearFlags.SolidColor;camera.transform.position=player.transform.position+new Vector3(0,10,-9);camera.transform.rotation=Quaternion.Euler(43f,0,0);camera.gameObject.AddComponent<AudioListener>();camera.gameObject.AddComponent<ArenaCamera>().target=player.transform;runtime.view=camera;
  if(!AssetDatabase.LoadAssetAtPath<TMP_FontAsset>("Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset")) TMP_PackageResourceImporter.ImportResources(true,false,false);
  var canvasGo=new GameObject("Test HUD",typeof(Canvas),typeof(UnityEngine.UI.CanvasScaler));var canvas=canvasGo.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var scaler=canvasGo.GetComponent<UnityEngine.UI.CanvasScaler>();scaler.uiScaleMode=UnityEngine.UI.CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1600,900);scaler.matchWidthOrHeight=.5f;
  var hud=canvasGo.AddComponent<ArenaHUD>();hud.player=runtime;
  Label(canvas.transform,"WOOLLY / TRAINING",new Vector2(28,-24),new Vector2(500,48),32,TextAlignmentOptions.TopLeft);
  Label(canvas.transform,"MOVEMENT + COMBAT LAB",new Vector2(30,-70),new Vector2(500,30),16,TextAlignmentOptions.TopLeft).color=new Color(.76f,.9f,.86f);
  hud.status=Label(canvas.transform,"IDLE",new Vector2(-28,-24),new Vector2(250,45),28,TextAlignmentOptions.TopRight,true);
  hud.stats=Label(canvas.transform,"SHOTS 0   HITS 0",new Vector2(-28,-69),new Vector2(350,30),17,TextAlignmentOptions.TopRight,true);
  hud.ammo=Label(canvas.transform,"6 / 6",new Vector2(-28,34),new Vector2(300,50),34,TextAlignmentOptions.BottomRight,true,true);
  Label(canvas.transform,"WASD  MOVE     SHIFT  RUN     MOUSE  AIM     LMB  FIRE     R  RELOAD",new Vector2(28,30),new Vector2(1100,40),20,TextAlignmentOptions.BottomLeft,false,true);
  var ret=Label(canvas.transform,"+",Vector2.zero,new Vector2(40,40),34,TextAlignmentOptions.Center);hud.reticle=ret.rectTransform;hud.reticle.pivot=new Vector2(.5f,.5f);ret.color=new Color(1,.88f,.36f);
  PrefabUtility.SaveAsPrefabAsset(player,Root+"Prefabs/Woolly_Player.prefab");
  EditorSceneManager.SaveScene(scene,Root+"Scenes/TrainingArena.unity");EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene(Root+"Scenes/TrainingArena.unity",true)};PlayerSettings.productName="Woolly Training Arena";PlayerSettings.companyName="Trexo";Application.targetFrameRate=60;QualitySettings.vSyncCount=1;AssetDatabase.SaveAssets();Selection.activeGameObject=player;SceneView.lastActiveSceneView?.Frame(new Bounds(new Vector3(0,0,1),new Vector3(20,5,20)),false);return "Arena built. Clips: "+string.Join(",",imported.Keys);
 }
 static TMP_Text Label(Transform parent,string text,Vector2 pos,Vector2 size,int font,TextAlignmentOptions alignment,bool right=false,bool bottom=false){var g=new GameObject(text,typeof(RectTransform),typeof(TextMeshProUGUI));g.transform.SetParent(parent,false);var r=g.GetComponent<RectTransform>();r.anchorMin=r.anchorMax=r.pivot=new Vector2(right?1:0,bottom?0:1);r.anchoredPosition=pos;r.sizeDelta=size;var t=g.GetComponent<TextMeshProUGUI>();t.font=AssetDatabase.LoadAssetAtPath<TMP_FontAsset>("Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset");t.text=text;t.fontSize=font;t.alignment=alignment;t.color=Color.white;t.raycastTarget=false;return t;}
}
}
