using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;
namespace WoollyArena.Editor {
public static class BreakablePropsSetup {
 static ParticleSystem FX(Transform parent,string name,Material mat,int count,Color tint,bool shards,Mesh shard){var go=new GameObject(name);go.transform.SetParent(parent,false);go.transform.localPosition=Vector3.up*.45f;var ps=go.AddComponent<ParticleSystem>();ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);var main=ps.main;main.playOnAwake=false;main.loop=false;main.duration=.15f;main.startLifetime=shards?.8f:.6f;main.startSpeed=shards?2:1;main.startSize=shards?.10f:.35f;main.startColor=tint;main.gravityModifier=shards?1:.02f;main.simulationSpace=ParticleSystemSimulationSpace.World;main.maxParticles=24;var emission=ps.emission;emission.rateOverTime=0;emission.SetBursts(new[]{new ParticleSystem.Burst(0,(short)count)});var shape=ps.shape;shape.shapeType=ParticleSystemShapeType.Hemisphere;shape.radius=.2f;var color=ps.colorOverLifetime;color.enabled=true;var g=new Gradient();g.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(Color.white,1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(0,1)});color.color=g;var rr=ps.GetComponent<ParticleSystemRenderer>();rr.sharedMaterial=mat;rr.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;if(shards){rr.renderMode=ParticleSystemRenderMode.Mesh;rr.mesh=shard;}return ps;}
 static Material Mat(string name,string hex){string p="Assets/Woolly/Materials/"+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(p);if(!m){m=new Material(Shader.Find("Woolly/ArenaToon"));AssetDatabase.CreateAsset(m,p);}ColorUtility.TryParseHtmlString(hex,out var color);m.shader=Shader.Find("Universal Render Pipeline/Lit");m.SetColor("_BaseColor",color);m.SetFloat("_Smoothness",.12f);m.SetFloat("_Metallic",0);EditorUtility.SetDirty(m);return m;}
 public static string Apply(){if(EditorApplication.isPlaying)throw new System.Exception("Stop Play before editing props");
 var root=GameObject.Find("Breakable Props");if(!root)root=new GameObject("Breakable Props");
 var wood=Mat("Breakable warm wood","#B66E3D");var trim=Mat("Breakable sunlit wood","#E8A661");var metal=Mat("Breakable blue bands","#536977");
 var dustMat=AssetDatabase.LoadAssetAtPath<Material>("Assets/Woolly/Materials/FootstepDust.mat");
 var cube=GameObject.CreatePrimitive(PrimitiveType.Cube);var shard=cube.GetComponent<MeshFilter>().sharedMesh;Object.DestroyImmediate(cube);
 var existing=root.GetComponentsInChildren<BreakableProp>();
 Vector3[] positions={new Vector3(-8.3f,0,0),new Vector3(8.3f,0,0),new Vector3(-6.65f,0,5.5f),new Vector3(6.65f,0,5.5f),new Vector3(-6.65f,0,4.2f),new Vector3(6.65f,0,4.2f),new Vector3(-7.65f,0,-5.7f),new Vector3(7.65f,0,-5.7f)};
 for(int i=0;i<8;i++){bool barrel=i<2||i==4||i==5;var b=i<existing.Length?existing[i]:new GameObject().AddComponent<BreakableProp>();var go=b.gameObject;go.name=barrel?"Breakable Barrel":"Breakable Crate";go.transform.SetParent(root.transform);go.transform.position=positions[i];var old=go.transform.Find("Painted prop");if(old)Object.DestroyImmediate(old.gameObject);old=go.transform.Find("Prop Model");if(old)Object.DestroyImmediate(old.gameObject);
 var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Woolly/Art/Environment/"+(barrel?"WoodBarrel":"SupplyCrate")+".fbx");var art=(GameObject)PrefabUtility.InstantiatePrefab(prefab);art.name="Prop Model";art.transform.SetParent(go.transform,false);art.transform.localPosition=Vector3.zero;art.transform.localRotation=Quaternion.Euler(0,barrel?0:(i%2==0?-8:8),0)*prefab.transform.localRotation;art.transform.localScale=Vector3.one*(barrel?1.3f:1.55f);
 var renderers=art.GetComponentsInChildren<Renderer>();foreach(var rr in renderers){rr.sharedMaterials=rr.sharedMaterials.Select(m=>m.name.Contains("Iron")?metal:m.name.Contains("Light")?trim:wood).ToArray();rr.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.On;rr.receiveShadows=true;}b.artwork=renderers[0];b.maxHealth=barrel?75:50;
 var bounds=renderers[0].bounds;foreach(var rr in renderers)bounds.Encapsulate(rr.bounds);var col=go.GetComponent<BoxCollider>();if(!col)col=go.AddComponent<BoxCollider>();col.center=go.transform.InverseTransformPoint(bounds.center);col.size=bounds.size;col.enabled=true;
 if(!b.dust)b.dust=FX(go.transform,"Break dust",dustMat,10,new Color(.88f,.64f,.37f,.6f),false,shard);if(!b.fragments)b.fragments=FX(go.transform,"Wood chips",dustMat,12,new Color(.45f,.22f,.08f,1),true,shard);
 }
 EditorSceneManager.MarkSceneDirty(root.scene);EditorSceneManager.SaveOpenScenes();AssetDatabase.SaveAssets();return "8 solid shadow-casting models in symmetric cover-side groups";
 }
}}
