using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using TMPro;using System.Linq;
namespace WoollyArena.Editor {
public static class CharacterPresentationSetup {
 static RectTransform Rect(string name,Transform parent,Vector2 pos,Vector2 size){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);r.anchoredPosition=pos;r.sizeDelta=size;return r;}
 static TMP_Text Text(string name,Transform parent,Vector2 pos,int size,Color color){var r=Rect(name,parent,pos,new Vector2(160,28));var t=r.gameObject.AddComponent<TextMeshProUGUI>();t.font=AssetDatabase.LoadAssetAtPath<TMP_FontAsset>("Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset");t.text=name;t.fontSize=size;t.fontStyle=FontStyles.Bold;t.color=color;t.alignment=TextAlignmentOptions.Center;t.raycastTarget=false;var mat=new Material(t.fontSharedMaterial);mat.EnableKeyword("OUTLINE_ON");mat.SetFloat("_OutlineWidth",.2f);mat.SetColor("_OutlineColor",new Color(.13f,.07f,.18f));string path="Assets/Woolly/Materials/"+name+" text.mat";AssetDatabase.CreateAsset(mat,path);t.fontSharedMaterial=mat;return t;}
 static UnityEngine.UI.Image Image(string name,Transform parent,Vector2 pos,Vector2 size,Color color){var r=Rect(name,parent,pos,size);var im=r.gameObject.AddComponent<UnityEngine.UI.Image>();im.color=color;im.raycastTarget=false;return im;}
 public static string Apply(){var p=Object.FindFirstObjectByType<ArenaPlayer>();var v=p.GetComponent<CharacterVitals>();if(!v)v=p.gameObject.AddComponent<CharacterVitals>();
 if(!p.GetComponentInChildren<CharacterBillboard>()){
 var root=Rect("Character Nameplate",p.transform,Vector2.zero,new Vector2(160,74));root.localPosition=new Vector3(0,2.05f,0);root.localScale=Vector3.one*.009f;var canvas=root.gameObject.AddComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.sortingOrder=20;var b=root.gameObject.AddComponent<CharacterBillboard>();b.player=p;b.vitals=v;b.nameLabel=Text("WOOLLY",root,new Vector2(0,28),20,new Color(.4f,1,.55f));b.healthLabel=Text("3000",root,new Vector2(0,7),18,Color.white);
 var back=Image("Health border",root,new Vector2(0,-13),new Vector2(112,16),new Color(.13f,.075f,.19f));var container=Rect("Health inset",back.transform,Vector2.zero,new Vector2(104,9));var fill=Image("Health fill",container,Vector2.zero,Vector2.zero,new Color(.35f,.94f,.4f));b.healthFill=fill.rectTransform;b.healthFill.anchorMin=Vector2.zero;b.healthFill.anchorMax=Vector2.one;b.healthFill.offsetMin=b.healthFill.offsetMax=Vector2.zero;
 b.ammoPips=new UnityEngine.UI.Image[6];for(int i=0;i<6;i++)b.ammoPips[i]=Image("Ammo "+i,root,new Vector2(-45+i*18,-27),new Vector2(14,5),Color.yellow);
 }
 if(!p.GetComponent<FootstepDust>()){
 var f=p.gameObject.AddComponent<FootstepDust>();f.player=p;var bones=p.visual.GetComponentsInChildren<Transform>();f.leftFoot=bones.First(t=>t.name=="mixamorig:LeftFoot");f.rightFoot=bones.First(t=>t.name=="mixamorig:RightFoot");var g=new GameObject("Footstep Dust");g.transform.SetParent(p.transform,false);var ps=g.AddComponent<ParticleSystem>();ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);var main=ps.main;main.loop=true;main.playOnAwake=true;main.simulationSpace=ParticleSystemSimulationSpace.World;main.maxParticles=48;main.startSpeed=0;var em=ps.emission;em.enabled=false;var shape=ps.shape;shape.enabled=false;var size=ps.sizeOverLifetime;size.enabled=true;size.size=new ParticleSystem.MinMaxCurve(1,new AnimationCurve(new Keyframe(0,.6f),new Keyframe(1,1.5f)));var color=ps.colorOverLifetime;color.enabled=true;var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(Color.white,1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(0,1)});color.color=gradient;var mat=new Material(Shader.Find("Woolly/SoftDust"));AssetDatabase.CreateAsset(mat,"Assets/Woolly/Materials/FootstepDust.mat");var renderer=ps.GetComponent<ParticleSystemRenderer>();renderer.sharedMaterial=mat;renderer.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;f.dust=ps;
 }
 var art=GameObject.Find("Environment_Art");if(art)foreach(Transform t in art.transform)if(t.name=="Sandstone flake")t.gameObject.SetActive(false);
 PrefabUtility.SaveAsPrefabAsset(p.gameObject,"Assets/Woolly/Prefabs/Woolly_Player.prefab");EditorSceneManager.MarkSceneDirty(p.gameObject.scene);EditorSceneManager.SaveOpenScenes();AssetDatabase.SaveAssets();return "Name, health/ammo plate and foot contact dust ready";}
}
}
