using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using System.Linq;
namespace WoollyArena.Editor {
public static class EnemySetup {
 public static string Apply(){if(EditorApplication.isPlaying)throw new System.Exception("Stop play first");
 var player=Object.FindFirstObjectByType<ArenaPlayer>();var go=Object.Instantiate(player.gameObject);go.name="Woolly Enemy";foreach(var t in go.GetComponentsInChildren<Transform>(true))t.gameObject.layer=0;
 var control=go.GetComponent<ArenaPlayer>();var plate=go.GetComponentInChildren<CharacterBillboard>();var enemy=go.AddComponent<EnemyAgent>();enemy.visual=control.visual;enemy.animator=control.animator;enemy.vitals=go.GetComponent<CharacterVitals>();enemy.vitals.maxHealth=100;enemy.vitals.displayName="RAIDER";enemy.nameLabel=plate.nameLabel;enemy.healthLabel=plate.healthLabel;enemy.healthFill=plate.healthFill;enemy.nameplate=plate.GetComponent<Canvas>();enemy.nameLabel.color=new Color(1,.47f,.43f);enemy.healthFill.GetComponent<UnityEngine.UI.Image>().color=new Color(.94f,.2f,.25f);foreach(var pip in plate.ammoPips)Object.DestroyImmediate(pip.gameObject);Object.DestroyImmediate(plate);Object.DestroyImmediate(control);
 foreach(var c in go.GetComponents<FootstepDust>())Object.DestroyImmediate(c);foreach(var c in go.GetComponents<FootprintTrail>())Object.DestroyImmediate(c);foreach(var c in go.GetComponents<BreakablePropProbe>())Object.DestroyImmediate(c);foreach(var c in go.GetComponents<ArenaSmokeProbe>())Object.DestroyImmediate(c);foreach(var c in go.GetComponents<PresentationProbe>())Object.DestroyImmediate(c);
 foreach(string child in new[]{"Selection Ring","Footstep Dust"}){var t=go.transform.Find(child);if(t)Object.DestroyImmediate(t.gameObject);}
 string mp="Assets/Woolly/Materials/Enemy Body.mat";var material=AssetDatabase.LoadAssetAtPath<Material>(mp);if(!material){material=new Material(AssetDatabase.LoadAssetAtPath<Material>("Assets/Woolly/Materials/Woolly Body.mat"));AssetDatabase.CreateAsset(material,mp);}material.SetColor("_BaseColor",new Color(1,.52f,.43f));EditorUtility.SetDirty(material);var body=go.GetComponentsInChildren<SkinnedMeshRenderer>().First(r=>r.name=="Woolly_Body");body.sharedMaterial=material;
 var prefab=PrefabUtility.SaveAsPrefabAsset(go,"Assets/Woolly/Prefabs/Woolly_Enemy.prefab");Object.DestroyImmediate(go);var director=Object.FindFirstObjectByType<EnemySpawnDirector>();if(!director)director=new GameObject("Enemy Spawner").AddComponent<EnemySpawnDirector>();director.prefab=prefab.GetComponent<EnemyAgent>();director.player=player.transform;director.spawnPoints=new[]{new Vector3(-8,.05f,7.8f),new Vector3(8,.05f,7.8f),new Vector3(-2,.05f,7.8f),new Vector3(2,.05f,7.8f),new Vector3(-8,.05f,-3),new Vector3(8,.05f,-3),new Vector3(-2,.05f,-7.5f),new Vector3(2,.05f,-7.5f),new Vector3(-3,.05f,2.2f),new Vector3(3,.05f,2.2f)};director.maxEnemies=4;director.respawnDelay=3;
 EditorSceneManager.MarkSceneDirty(player.gameObject.scene);EditorSceneManager.SaveOpenScenes();AssetDatabase.SaveAssets();return "Enemy prefab and 10 spawn points, 4 active enemies with respawn";
 }
}}
