using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.EventSystems;using WoollyArena;using System.Linq;
public static class CombatLobbyChecks {
 static int checks;static void Check(bool ok,string name){if(!ok)throw new System.Exception("FAIL: "+name);checks++;}
 public static void Run(){
 var go=new GameObject("Button Test",typeof(RectTransform));var stick=go.AddComponent<TouchStick>();stick.knob=new GameObject("Knob",typeof(RectTransform)).GetComponent<RectTransform>();stick.knob.SetParent(go.transform);stick.buttonOnly=true;var es=new GameObject("Test Events").AddComponent<EventSystem>();var e=new PointerEventData(es){pointerId=7,position=new Vector2(950,120)};stick.OnPointerDown(e);Check(stick.Held&&stick.Value==Vector2.zero,"fire does not steer");e.position=new Vector2(-600,500);stick.OnDrag(e);Check(stick.Value==Vector2.zero&&stick.knob.anchoredPosition==Vector2.zero,"drag ignores aim");stick.OnPointerUp(new PointerEventData(es){pointerId=8});Check(stick.Held,"other finger cannot release fire");stick.OnPointerUp(e);Check(!stick.Held&&stick.ConsumePress()&&!stick.ConsumePress(),"quick tap consumed once");stick.OnPointerDown(e);stick.ResetInput();Check(!stick.Held&&!stick.ConsumePress(),"pause cancels input");Object.DestroyImmediate(go);Object.DestroyImmediate(es.gameObject);
 EditorSceneManager.OpenScene("Assets/Woolly/Scenes/Lobby.unity");var lobby=Object.FindFirstObjectByType<LobbyScreen>();Check(lobby&&lobby.hero&&lobby.animator,"lobby rig and animator");Check(lobby.art.All(x=>x),"all lobby sprites");Check(lobby.font.HasCharacters("MAĞAZA ARKADAŞLAR GÖREVLER LOBİ",out uint[] missing,true),"Turkish font glyphs");Check(Object.FindObjectsByType<EventSystem>().Length==1,"one EventSystem");Check(lobby.GetComponentsInChildren<UnityEngine.UI.Button>().Any(b=>b.name=="Play"),"play button");Check(EditorBuildSettings.scenes.Length==2&&EditorBuildSettings.scenes[0].path.EndsWith("Lobby.unity"),"lobby entry scene");
 var bounds=new Bounds(lobby.hero.position,Vector3.zero);foreach(var r in lobby.hero.GetComponentsInChildren<Renderer>())bounds.Encapsulate(r.bounds);Check(bounds.size.y>.5f&&bounds.size.y<4,"hero bounds");
 System.IO.File.WriteAllText("Logs/combat-lobby-checks.txt",checks+" checks passed\nHero bounds: "+bounds+"\n");
 }
}
